./management-report runner -w daily -s active_users
./management-report runner -w daily -s posts_expired
./management-report runner -w daily -s claims
./management-report runner -w daily -s checkouts
./management-report runner -w daily -s unique_posters
./management-report runner -w daily -s unique_claimers
./management-report runner -w daily -s unique_transactors
./management-report runner -w daily -s total_revenue
./management-report runner -w daily -s revenue_refunds
./management-report runner -w daily -s gmv
./management-report runner -w daily -s posts_all
./management-report runner -w daily -s posts_up_granting
./management-report runner -w daily -s posts_first_owners
./management-report runner -w daily -s posts_subsequent_owners
./management-report runner -w daily -s wishes_granted
./management-report runner -w daily -s posts_deleted
./management-report runner -w daily -s posts_unclaimed_count_end
./management-report runner -w daily -s users_count_start
./management-report runner -w daily -s users_signups
./management-report runner -w daily -s users_signups_referred
./management-report runner -w daily -s users_signups_affiliates
./management-report runner -w daily -s users_signups_paid
./management-report runner -w daily -s users_removals
./management-report runner -w daily -s users_count_end
./management-report runner -w daily -s new_users_return_0
./management-report runner -w daily -s new_users_return_5
./management-report runner -w daily -s new_users_return_10
./management-report runner -w daily -s new_users_return_15
./management-report runner -w daily -s new_users_return_30
./management-report runner -w daily -s new_users_return_60
./management-report runner -w daily -s new_users_posters
./management-report runner -w daily -s new_users_unique_claimers
./management-report runner -w daily -s new_users_posts
./management-report runner -w daily -s new_users_items_claimed
./management-report runner -w daily -s return_user
./management-report runner -w daily -s return_users_unique_posters
./management-report runner -w daily -s return_users_unique_claimers
./management-report runner -w daily -s return_users_posts
./management-report runner -w daily -s return_users_items_claimed
./management-report runner -w daily -s retained_new_users
./management-report runner -w daily -s retained_new_users_unique_posters
./management-report runner -w daily -s retained_new_users_unique_claimers
./management-report runner -w daily -s retained_new_users_posts
./management-report runner -w daily -s retained_new_users_items_claimed
./management-report runner -w daily -s retained_ongoing_users
./management-report runner -w daily -s retained_ongoing_users_unique_posters
./management-report runner -w daily -s retained_ongoing_users_unique_claimers
./management-report runner -w daily -s retained_ongoing_users_posts
./management-report runner -w daily -s retained_ongoing_users_items_claimed
./management-report runner -w daily -s reactivated_users
./management-report runner -w daily -s reactivated_users_unique_posters
./management-report runner -w daily -s reactivated_users_unique_claimers
./management-report runner -w daily -s reactivated_users_posts
./management-report runner -w daily -s reactivated_users_items_claimed
./management-report runner -w daily -s pro_users_count
./management-report runner -w daily -s pro_users_new
./management-report runner -w daily -s pro_users_active
./management-report runner -w daily -s pro_users_flub_5
./management-report runner -w daily -s pro_users_claims
./management-report runner -w daily -s star_users_count
./management-report runner -w daily -s star_users_new
./management-report runner -w daily -s star_users_active
./management-report runner -w daily -s star_users_claims
./management-report runner -w daily -s checkouts_bundles
./management-report runner -w daily -s checkouts_first_claimers
./management-report runner -w daily -s checkouts_first_claimers_ships_free
./management-report runner -w daily -s bundles_items_avg
./management-report runner -w daily -s ships_paid_checkouts
./management-report runner -w daily -s ships_free_checkouts
./management-report runner -w daily -s ships_1_checkouts
./management-report runner -w daily -s ships_2_checkouts
./management-report runner -w daily -s ships_250_checkouts
./management-report runner -w daily -s ships_3_checkouts
./management-report runner -w daily -s ships_4_checkouts
./management-report runner -w daily -s ships_5_checkouts
./management-report runner -w daily -s ships_6_checkouts
./management-report runner -w daily -s ships_pickups
./management-report runner -w daily -s checkouts_bundles_ships_paid
./management-report runner -w daily -s checkouts_bundles_ships_free
./management-report runner -w daily -s fulfillment_items
./management-report runner -w daily -s fulfillment_ships
./management-report runner -w daily -s fulfillment_pickups
./management-report runner -w daily -s revenue_shipping
./management-report runner -w daily -s revenue_service
./management-report runner -w daily -s revenue_bundling
./management-report runner -w daily -s revenue_yrd
./management-report runner -w daily -s checkouts_service_bundling_revenue
./management-report runner -w daily -s checkouts_shipping_revenue

